Repository dwyl/phoenix-ecto-encryption-example, pull requests merged in 2022-06, with the labels that each got.

#23 Add new :crypto syntax to README
  README.md
Labels: help wanted, merge-conflicts

#21 Refactor user.ex
  lib/encryption/user.ex
Labels: help wanted, awaiting-review, technical, T25m, priority-2, merge-conflicts

#47 PR: Update `Phoenix` Version + Mention `fields` in `README.md` #36
  .github/dependabot.yml
  .github/workflows/ci.yml
  .travis.yml
  README.md
  config/config.exs
  config/dev.exs
  config/prod.exs
  config/test.exs
  coveralls.json
  lib/encryption/aes.ex
  lib/encryption/application.ex
  lib/encryption/encrypted_field.ex
  lib/encryption/user.ex
  lib/encryption_web/router.ex
  lib/encryption_web/templates/layout/app.html.eex
  mix.exs
  mix.lock
  test/encryption_web/views/layout_view_test.exs
  test/encryption_web/views/page_view_test.exs
  test/lib/encrypted_field_test.exs
  test/lib/hash_field_test.exs
  test/lib/password_field_test.exs
  test/support/conn_case.ex
  test/user/user_test.exs
Labels: enhancement, chore, awaiting-review, technical, T25m

#51 Updates to README.md
  README.md
Labels: awaiting-review
